[package]
description = "my rust study codes"
edition = "2021"
license = "MIT"
name = "rust-sample"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
